import { z } from 'zod'

export const SaleReportParser = z.object({
  amount_you_received: z.number(),
  artist: z.string().nullable(),
  bandcamp_transaction_id: z.string().or(z.number()),
  buyer_email: z.string().nullable(),
  buyer_name: z.string().nullable(),
  buyer_note: z.string().nullable(),
  buyer_phone: z.string().nullable(),
  catalog_number: z.string().nullable(),
  city: z.string().nullable(),
  country_code: z.string().nullable(),
  country: z.string().nullable(),
  currency: z.string(),
  date: z.string(),
  discount_code: z.string().nullable(),
  fee_type: z.string().nullable(),
  isrc: z.string().nullable(),
  item_name: z.string().nullable(),
  item_price: z.number().nullable(),
  item_total: z.number(),
  item_type: z.string(),
  item_url: z.string().nullable(),
  marketplace_tax: z.number().nullable(),
  net_amount: z.number().nullable(),
  option: z.unknown(),
  package: z.string().nullable(),
  paid_to: z.string(),
  paypal_transaction_id: z.string().nullable(),
  quantity: z.number().nullable(),
  referer_url: z.string().nullable(),
  referer: z.string().nullable(),
  region_or_state: z.string().nullable(),
  seller_tax: z.number().nullable(),
  ship_date: z.string().nullable(),
  ship_from_country_name: z.string().nullable(),
  ship_notes: z.string().nullable(),
  ship_to_city: z.string().nullable(),
  ship_to_country_code: z.string().nullable(),
  ship_to_country: z.string().nullable(),
  ship_to_name: z.string().nullable(),
  ship_to_state: z.string().nullable(),
  ship_to_street_2: z.string().nullable(),
  ship_to_street: z.string().nullable(),
  ship_to_zip: z.string().nullable(),
  shipping: z.number().nullable(),
  sku: z.string().nullable(),
  sub_total: z.number().nullable(),
  transaction_fee: z.number().nullable(),
  upc: z.string().nullable(),
})

export type SaleReport = z.output<typeof SaleReportParser>
